I'm assuming there will be another TypeError, 3 arguments were provided
where the function was expecting only 2 arguments.

TypeError: foo() takes 2 positional arguments, but 3 were given
